# Goals of this Activity


## 1. Implement convolution
Given an n,m RGB image as a numpy array and a k x k x 3 convolution filter. Implement the
convolution operation with ‘same’ padding without using higher level functions like conv2d from tensorflow, or convolve from numpy. 

In [13]:
import numpy as np 

def convolve(im, kernel):
    m, n = kernel.shape[0], kernel.shape[1]
    y, x = im.shape[0], im.shape[1]
    y = y - m + 1
    x = x - m + 1
    new_image = np.zeros((y,x))
    for i in range(y):
        for j in range(x):
            new_image[i][j] = np.sum(im[i:i+m, j:j+m]*kernel)
            #print(image[i:i+m, j:j+m])
    return new_image

im = np.array([[1, 2, 0, 0], [5, 3, 0, 4], [0, 0, 0, 7], [9, 3, 0, 0]])
kernel = np.array([[1,1,1],[1,1,0],[1,0,0]])
kernel = np.fliplr(kernel) # flip leftright
kernel = np.flipud(kernel) # flip up down

pad = 3-1/2 #f-1/2
im = np.pad(im, ((1, 1), (1, 1)), 'constant') # pad each side with zeros
print(im)
print(kernel)
result = convolve(im, kernel)
print(result)

[[0 0 0 0 0 0]
 [0 1 2 0 0 0]
 [0 5 3 0 4 0]
 [0 0 0 0 7 0]
 [0 9 3 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 1]
 [0 1 1]
 [1 1 1]]
[[11. 10.  7.  4.]
 [10.  3. 11. 11.]
 [15. 12. 14.  7.]
 [12.  3.  7.  0.]]


## 2. Implement max_pool 
Given a grayscale image as a numpy array. We are also given a k by k max pooling filter with a stride of 1. Implement the max_pool operation without using higher level functions like block_reduce.

In [14]:
def max_pool(im, k):
    y, x = im.shape[0], im.shape[1]
    f = k
    s = k
    y = int((y - f)/s) + 1
    x = int((x - f)/s) + 1
    new_image = np.zeros((y,x))

    imgy = im.shape[0]
    imgx = im.shape[1]  
    for i in range(0,imgy,2):
        for j in range(0,imgx,2):
            m = int(i/s)
            n = int(j/s)
            new_image[m][n] = np.max(im[i:i + s, j:j + s])
    return new_image



im = np.array([[1, 2, 0, 0], [5, 3, 0, 4], [0, 0, 0, 7], [9, 3, 0, 0]])
k = 2

result = max_pool(im, k)
print(im)
print( result)


[[1 2 0 0]
 [5 3 0 4]
 [0 0 0 7]
 [9 3 0 0]]
[[5. 4.]
 [9. 7.]]
